/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SettingsImport } from './routes/settings'
import { Route as IndexImport } from './routes/index'
import { Route as SettingsIndexImport } from './routes/settings.index'
import { Route as ProductsIndexImport } from './routes/products.index'
import { Route as EmployeesIndexImport } from './routes/employees.index'
import { Route as SettingsClaimsIndexImport } from './routes/settings.claims.index'
import { Route as SettingsAppearanceIndexImport } from './routes/settings.appearance.index'
import { Route as ProductsProductIdIndexImport } from './routes/products.$productId.index'
import { Route as EmployeesEmployeeIdIndexImport } from './routes/employees.$employeeId.index'
import { Route as SettingsClaimsServerIndexImport } from './routes/settings.claims.server.index'
import { Route as SettingsClaimsLocalIndexImport } from './routes/settings.claims.local.index'

// Create/Update Routes

const SettingsRoute = SettingsImport.update({
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SettingsIndexRoute = SettingsIndexImport.update({
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)

const ProductsIndexRoute = ProductsIndexImport.update({
  path: '/products/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/products.index.lazy').then((d) => d.Route),
)

const EmployeesIndexRoute = EmployeesIndexImport.update({
  path: '/employees/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/employees.index.lazy').then((d) => d.Route),
)

const SettingsClaimsIndexRoute = SettingsClaimsIndexImport.update({
  path: '/claims/',
  getParentRoute: () => SettingsRoute,
} as any)

const SettingsAppearanceIndexRoute = SettingsAppearanceIndexImport.update({
  path: '/appearance/',
  getParentRoute: () => SettingsRoute,
} as any).lazy(() =>
  import('./routes/settings.appearance.index.lazy').then((d) => d.Route),
)

const ProductsProductIdIndexRoute = ProductsProductIdIndexImport.update({
  path: '/products/$productId/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/products.$productId.index.lazy').then((d) => d.Route),
)

const EmployeesEmployeeIdIndexRoute = EmployeesEmployeeIdIndexImport.update({
  path: '/employees/$employeeId/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/employees.$employeeId.index.lazy').then((d) => d.Route),
)

const SettingsClaimsServerIndexRoute = SettingsClaimsServerIndexImport.update({
  path: '/claims/server/',
  getParentRoute: () => SettingsRoute,
} as any).lazy(() =>
  import('./routes/settings.claims.server.index.lazy').then((d) => d.Route),
)

const SettingsClaimsLocalIndexRoute = SettingsClaimsLocalIndexImport.update({
  path: '/claims/local/',
  getParentRoute: () => SettingsRoute,
} as any).lazy(() =>
  import('./routes/settings.claims.local.index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/employees/': {
      preLoaderRoute: typeof EmployeesIndexImport
      parentRoute: typeof rootRoute
    }
    '/products/': {
      preLoaderRoute: typeof ProductsIndexImport
      parentRoute: typeof rootRoute
    }
    '/settings/': {
      preLoaderRoute: typeof SettingsIndexImport
      parentRoute: typeof SettingsImport
    }
    '/employees/$employeeId/': {
      preLoaderRoute: typeof EmployeesEmployeeIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/products/$productId/': {
      preLoaderRoute: typeof ProductsProductIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/settings/appearance/': {
      preLoaderRoute: typeof SettingsAppearanceIndexImport
      parentRoute: typeof SettingsImport
    }
    '/settings/claims/': {
      preLoaderRoute: typeof SettingsClaimsIndexImport
      parentRoute: typeof SettingsImport
    }
    '/settings/claims/local/': {
      preLoaderRoute: typeof SettingsClaimsLocalIndexImport
      parentRoute: typeof SettingsImport
    }
    '/settings/claims/server/': {
      preLoaderRoute: typeof SettingsClaimsServerIndexImport
      parentRoute: typeof SettingsImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  SettingsRoute.addChildren([
    SettingsIndexRoute,
    SettingsAppearanceIndexRoute,
    SettingsClaimsIndexRoute,
    SettingsClaimsLocalIndexRoute,
    SettingsClaimsServerIndexRoute,
  ]),
  EmployeesIndexRoute,
  ProductsIndexRoute,
  EmployeesEmployeeIdIndexRoute,
  ProductsProductIdIndexRoute,
])

/* prettier-ignore-end */
