version: '3.9'

services:
  db:
    container_name: db
    image: chriseaton/adventureworks:light
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'Letmeinprettypleas3!'
    restart: always
